-- MySQL Script generated by MySQL Workbench
-- Mon Feb  7 12:15:01 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`PLANET_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PLANET_TYPE` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(30) NOT NULL,
  `Description` TEXT(1000) NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RESEARCH_GROUP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RESEARCH_GROUP` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(30) NOT NULL,
  `Description` TEXT(1000) NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TYPE_USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TYPE_USER` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(20) NOT NULL,
  `Description` TEXT(1000) NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USER` (
  `Id` INT NOT NULL,
  `Email` VARCHAR(30) NOT NULL,
  `PasswordHach` INT NOT NULL,
  `TupeUser` INT NOT NULL,
  `ResearchGroup` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_USER_RESEARCH_GROUP1_idx` (`ResearchGroup` ASC) VISIBLE,
  INDEX `fk_USER_TYPE_USER1_idx` (`TupeUser` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  CONSTRAINT `fk_USER_RESEARCH_GROUP1`
    FOREIGN KEY (`ResearchGroup`)
    REFERENCES `mydb`.`RESEARCH_GROUP` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_TYPE_USER1`
    FOREIGN KEY (`TupeUser`)
    REFERENCES `mydb`.`TYPE_USER` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EXOPLANET_DETECTION_METHOD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EXOPLANET_DETECTION_METHOD` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(30) NOT NULL,
  `Description` TEXT(1000) NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EXOPLANET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EXOPLANET` (
  `Id` INT NOT NULL,
  `Exoplanet_Name` VARCHAR(60) NOT NULL,
  `Exoplanet_Status` TINYINT NOT NULL,
  `Exoplanet_DateAdded` DATE NOT NULL,
  `Exoplanet_DateСonfirmation` DATE NULL,
  `Exoplanet_Mass` FLOAT NULL,
  `Exoplanet_Radius` FLOAT NULL,
  `Exoplanet_OrbitalRadius` FLOAT NULL,
  `User` INT NOT NULL,
  `Exoplanet_DetectionMethod` INT NOT NULL,
  `Exoplanet_Type` VARCHAR(30) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_EXOPLANET_PLANET TYPE1_idx` (`Exoplanet_Type` ASC) VISIBLE,
  INDEX `fk_EXOPLANET_USER1_idx` (`User` ASC) VISIBLE,
  UNIQUE INDEX `Exoplanet_Name_UNIQUE` (`Exoplanet_Name` ASC) VISIBLE,
  INDEX `fk_EXOPLANET_EXOPLANET_DETECTION_METHOD1_idx` (`Exoplanet_DetectionMethod` ASC) VISIBLE,
  CONSTRAINT `fk_EXOPLANET_PLANET TYPE1`
    FOREIGN KEY (`Exoplanet_Type`)
    REFERENCES `mydb`.`PLANET_TYPE` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EXOPLANET_USER1`
    FOREIGN KEY (`User`)
    REFERENCES `mydb`.`USER` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EXOPLANET_EXOPLANET_DETECTION_METHOD1`
    FOREIGN KEY (`Exoplanet_DetectionMethod`)
    REFERENCES `mydb`.`EXOPLANET_DETECTION_METHOD` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`STAR_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`STAR_TYPE` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(30) NOT NULL,
  `Description` TEXT(1000) NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`STAR_DETECTION_METHOD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`STAR_DETECTION_METHOD` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(30) NOT NULL,
  `Description` TEXT(1000) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`STAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`STAR` (
  `Id` INT NOT NULL,
  `Star_Name` VARCHAR(60) NOT NULL,
  `Star_Status` TINYINT NOT NULL,
  `Star_DateAdded` DATE NOT NULL,
  `Star_DateСonfirmation` DATE NULL,
  `Star_Mass` FLOAT NULL,
  `Star_Radius` FLOAT NULL,
  `Star_DetectionMethod` INT NOT NULL,
  `User` INT NOT NULL,
  `Star_Type` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_STAR_STAR_TYPE1_idx` (`Star_Type` ASC) VISIBLE,
  INDEX `fk_STAR_STAR_DETECTION_METHOD1_idx` (`Star_DetectionMethod` ASC) VISIBLE,
  INDEX `fk_STAR_USER1_idx` (`User` ASC) VISIBLE,
  UNIQUE INDEX `Star_Name_UNIQUE` (`Star_Name` ASC) VISIBLE,
  CONSTRAINT `fk_STAR_STAR_TYPE1`
    FOREIGN KEY (`Star_Type`)
    REFERENCES `mydb`.`STAR_TYPE` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STAR_STAR_DETECTION_METHOD1`
    FOREIGN KEY (`Star_DetectionMethod`)
    REFERENCES `mydb`.`STAR_DETECTION_METHOD` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STAR_USER1`
    FOREIGN KEY (`User`)
    REFERENCES `mydb`.`USER` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`STAR_AND_EXOPLANET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`STAR_AND_EXOPLANET` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Star` INT NULL,
  `Exoplane` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_STAR_AND_EXOPLANET_STAR1_idx` (`Star` ASC) VISIBLE,
  INDEX `fk_STAR_AND_EXOPLANET_EXOPLANET1_idx` (`Exoplane` ASC) VISIBLE,
  CONSTRAINT `fk_STAR_AND_EXOPLANET_STAR1`
    FOREIGN KEY (`Star`)
    REFERENCES `mydb`.`STAR` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STAR_AND_EXOPLANET_EXOPLANET1`
    FOREIGN KEY (`Exoplane`)
    REFERENCES `mydb`.`EXOPLANET` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
