-- MySQL Script generated by MySQL Workbench
-- Thu Feb 10 19:20:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SAEDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SAEDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SAEDB` DEFAULT CHARACTER SET utf8mb4 ;
USE `SAEDB` ;

-- -----------------------------------------------------
-- Table `SAEDB`.`RESEARCH_GROUP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAEDB`.`RESEARCH_GROUP` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(25) NOT NULL,
  `Description` TEXT(300) NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAEDB`.`USER_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAEDB`.`USER_TYPE` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(20) NOT NULL,
  `Description` TEXT(300) NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAEDB`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAEDB`.`USER` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(20) NOT NULL,
  `Email` VARCHAR(30) NOT NULL,
  `PasswordHach` INT NOT NULL,
  `TupeUser` INT NOT NULL,
  `ResearchGroup` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_USER__RESEARCH_GROUP_idx` (`ResearchGroup` ASC) VISIBLE,
  INDEX `fk_USER__USER_TYPE_idx` (`TupeUser` ASC) INVISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  CONSTRAINT `fk_USER__RESEARCH_GROUP`
    FOREIGN KEY (`ResearchGroup`)
    REFERENCES `SAEDB`.`RESEARCH_GROUP` (`Id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_USER__USER_TYPE`
    FOREIGN KEY (`TupeUser`)
    REFERENCES `SAEDB`.`USER_TYPE` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAEDB`.`EXOPLANET_DETECTION_METHOD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAEDB`.`EXOPLANET_DETECTION_METHOD` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(25) NOT NULL,
  `Description` TEXT(300) NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAEDB`.`EXOPLANET_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAEDB`.`EXOPLANET_TYPE` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(25) NOT NULL,
  `Description` TEXT(300) NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAEDB`.`DISCOVERER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAEDB`.`DISCOVERER` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(25) NOT NULL,
  `Description` VARCHAR(300) NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAEDB`.`EXOPLANET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAEDB`.`EXOPLANET` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Exoplanet_Name` VARCHAR(30) NOT NULL,
  `Exoplanet_Status` TINYINT NOT NULL,
  `Exoplanet_DateAdded` DATE NOT NULL,
  `Exoplanet_DateСonfirmation` DATE NULL,
  `Exoplanet_Mass` FLOAT NULL,
  `Exoplanet_Radius` FLOAT NULL,
  `Exoplanet_OrbitalRadius` FLOAT NULL,
  `User` INT NULL,
  `Exoplanet_DetectionMethod` INT NULL,
  `Exoplanet_Type` INT NULL,
  `Exoplanet_discoverer` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_EXOPLANET__USER_idx` (`User` ASC) VISIBLE,
  UNIQUE INDEX `Exoplanet_Name_UNIQUE` (`Exoplanet_Name` ASC) INVISIBLE,
  INDEX `fk_EXOPLANET__EXOPLANET_DETECTION_METHOD_idx` (`Exoplanet_DetectionMethod` ASC) VISIBLE,
  INDEX `fk_EXOPLANET__EXOPLANET_TYPE_idx` (`Exoplanet_Type` ASC) VISIBLE,
  INDEX `fk_EXOPLANET__DISCOVERER_idx` (`Exoplanet_discoverer` ASC) VISIBLE,
  CONSTRAINT `fk_EXOPLANET__USER`
    FOREIGN KEY (`User`)
    REFERENCES `SAEDB`.`USER` (`Id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_EXOPLANET__EXOPLANET_DETECTION_METHOD`
    FOREIGN KEY (`Exoplanet_DetectionMethod`)
    REFERENCES `SAEDB`.`EXOPLANET_DETECTION_METHOD` (`Id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_EXOPLANET__EXOPLANET_TYPE`
    FOREIGN KEY (`Exoplanet_Type`)
    REFERENCES `SAEDB`.`EXOPLANET_TYPE` (`Id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_EXOPLANET__DISCOVERER`
    FOREIGN KEY (`Exoplanet_discoverer`)
    REFERENCES `SAEDB`.`DISCOVERER` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAEDB`.`STAR_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAEDB`.`STAR_TYPE` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(25) NOT NULL,
  `Description` TEXT(300) NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAEDB`.`STAR_DETECTION_METHOD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAEDB`.`STAR_DETECTION_METHOD` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(25) NOT NULL,
  `Description` TEXT(300) NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAEDB`.`STAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAEDB`.`STAR` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Star_Name` VARCHAR(30) NOT NULL,
  `Star_Status` TINYINT NOT NULL,
  `Star_DateAdded` DATE NOT NULL,
  `Star_DateСonfirmation` DATE NULL,
  `Star_Mass` FLOAT NULL,
  `Star_Radius` FLOAT NULL,
  `User` INT NULL,
  `Star_DetectionMethod` INT NULL,
  `Star_Type` INT NULL,
  `Star_discoverer` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_STAR__STAR_TYPE_idx` (`Star_Type` ASC) VISIBLE,
  INDEX `fk_STAR__STAR_DETECTION_METHOD_idx` (`Star_DetectionMethod` ASC) VISIBLE,
  INDEX `fk_STAR__USER_idx` (`User` ASC) INVISIBLE,
  UNIQUE INDEX `Star_Name_UNIQUE` (`Star_Name` ASC) INVISIBLE,
  INDEX `fk_STAR__DISCOVERER_idx` (`Star_discoverer` ASC) VISIBLE,
  CONSTRAINT `fk_STAR__STAR_TYPE`
    FOREIGN KEY (`Star_Type`)
    REFERENCES `SAEDB`.`STAR_TYPE` (`Id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_STAR__STAR_DETECTION_METHOD`
    FOREIGN KEY (`Star_DetectionMethod`)
    REFERENCES `SAEDB`.`STAR_DETECTION_METHOD` (`Id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_STAR__USER`
    FOREIGN KEY (`User`)
    REFERENCES `SAEDB`.`USER` (`Id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_STAR__DISCOVERER`
    FOREIGN KEY (`Star_discoverer`)
    REFERENCES `SAEDB`.`DISCOVERER` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAEDB`.`STAR_AND_EXOPLANET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAEDB`.`STAR_AND_EXOPLANET` (
  `Star` INT NOT NULL,
  `Exoplane` INT NOT NULL,
  PRIMARY KEY (`Star`, `Exoplane`),
  INDEX `fk_STAR_AND_EXOPLANET__STAR_idx` (`Star` ASC) VISIBLE,
  INDEX `fk_STAR_AND_EXOPLANET__EXOPLANET_idx` (`Exoplane` ASC) INVISIBLE,
  CONSTRAINT `fk_STAR_AND_EXOPLANET__STAR`
    FOREIGN KEY (`Star`)
    REFERENCES `SAEDB`.`STAR` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_STAR_AND_EXOPLANET__EXOPLANET`
    FOREIGN KEY (`Exoplane`)
    REFERENCES `SAEDB`.`EXOPLANET` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
